os: linux
dist: xenial
language: cpp
addons:
  apt:
    sources:
      - sourceline: 'ppa:zhaofeng-shu33/liblemon'
      - sourceline: 'ppa:zhaofeng-shu33/gtest'    
    packages:
      - liblemon-dev
      - liblemon1.3.1
      - libgtest-dev
      - lcov
script:
  - mkdir build
  - python graph_generator.py
  - cd build
  - cmake -DCODE_COVERAGE=ON -DENABLE_TESTING=ON ../
  - make
  - ./test_alg
after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info