version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
install:
- cmd: >-        
    IF NOT EXIST "C:\Tools\vcpkg\installed\x64-windows\include\lemon\config.h" vcpkg install liblemon:x64-windows gtest:x64-windows
    
cache: C:\Tools\vcpkg\installed\x64-windows
build: off
build_script:
- cmd: >-
    mkdir build
    
    C:\Python36-x64\python.exe graph_generator.py
    
    cd build
    
    cmake -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DENABLE_TESTING=ON ..
    
    cmake --build . --config=Release
    
    .\Release\test_alg.exe